server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always
spring:
  application:
    name: OpenAiChatService
  mvc:
    static-path-pattern: /static/**
  servlet:
    multipart:
      enabled: true
      max-file-size: 12MB
      max-request-size: 20MB
  cloud:
    bootstrap:
      enabled: true
    config:
      profile: dev
      discovery:
        enabled: true
        service-id: ConfigService
      enabled: true
      import-check:
        enabled: false

  config:
    import: "optional:configserver:http://localhost:8887"

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://143.198.58.6:8761/eureka/

logging:
  level:
    org:
      springframework:
        cloud: DEBUG
    com.amazonaws: DEBUG
    io.awspring.cloud: DEBUG


n8n:
    webhook:
      knowledgebase:
        train:
          url: http://143.198.58.6:5678/webhook/cacb416b-286a-4524-9b29-9d8a81bb5864
        chat:
          url: http://localhost:5678/webhook/beab6fcf-f27a-4d26-8923-5f95e8190fea
