server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always
spring:
  application:
    name: OpenAiChatService
  mvc:
    static-path-pattern: /static/**
  servlet:
    multipart:
      enabled: true
      max-file-size: 12MB
      max-request-size: 20MB
  cloud:
    bootstrap:
      enabled: false
    config:
      profile: dev
      discovery:
        enabled: false
      enabled: true
      uri: http://172.17.0.1:8887
      import-check:
        enabled: false

  config:
    import: "optional:configserver:http://172.17.0.1:8887/"

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://172.17.0.1:8761/eureka/

logging:
  level:
    org:
      springframework:
        cloud: DEBUG
    com.amazonaws: DEBUG
    io.awspring.cloud: DEBUG
